const publicUrl = process.env.PUBLIC_URL;

export const TEACHERSDATA = [
  {
    name: "Er. Vivek Sharma",
    position: "Dean CS & IT Services",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-1.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Dr. Gaurav Sharma",
    position: "HOD CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-2.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Er. Rajeev Bansal",
    position: "AP CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-3.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Ms. Pinki Tanwar",
    position: "AP CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-4.jpeg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Ms. Shabnam Parveen",
    position: "AP CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-5.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Ms. Meenakshi Rani",
    position: "AP CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-6.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Ms. Sonia Sharma",
    position: "AP CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-7.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Ms. Mamta Nain",
    position: "AP CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-8.jpeg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Ms. Nidhi Seth",
    position: "AP CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-9.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Ms. Shilpi Harnal",
    position: "AP CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-10.jpeg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Ms. Monika Choudhary",
    position: "AP CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-11.jpeg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Mr. Mohit Lalit",
    position: "AP CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-12.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Mr. Ajay Kumar",
    position: "AP CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-13.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
];
