const publicUrl = process.env.PUBLIC_URL;

export const TEACHERSDATA = [
  {
    name: "Er. Vivek Sharma",
    position: "Dean CS & IT Services",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-1.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Dr. Gaurav Sharma",
    position: "Dean CS & IT Services",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-2.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Er. Rajeev Bansal",
    position: "AP CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-3.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "Ms. Shilpi",
    position: "AP CSE",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-4.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
  {
    name: "XYZ",
    position: "---",
    intro: "I am an ambitious workaholic, but apart from that, pretty simple person.",
    image: publicUrl + "/images/teacher-5.jpg",
    twitter: "#",
    istagram: "#",
    facebook: "#",
    google: "#",
  },
];
